name: CFRandomTeleport
version: 0.0.1
author: Didz
description: Let players teleport to random locations on worlds.
website: http://collidingfate.org/
main: org.collidingfate.cfrandomteleport.CFRandomTeleport
softdepend: [WorldBorder]

commands:
  cfrtp:
    description: Teleport to a random location!
    permission: cfrandomteleport.teleport
    usage: "Usage: <command>"

permissions:
  cfrandomteleport.teleport:
    description: Allows the player to teleport to a random location.
    default: op
